<?php

namespace App\Cms\Structures;

use App\Models\Cms\FeedbackFormEmails;

class FeedbackCmsBlock extends CmsBlock {
	public $type = 'feedback';

	public $icon = 'fa fa-question';

	public $label = 'Блок с отправкой формы отзыва';

	public $template = 'feedback.html';

	public function seed($data) {
		parent::seed($data); // TODO: Change the autogenerated stub

		$this->config['code'] = empty($this->config['code']) ? hash_hmac('sha1', uniqid('form'), 'form') : $this->config['code'];
		$formEmailsConfig = FeedbackFormEmails::where(['code' => $this->config['code']])->first();
		$formEmailsConfig = $formEmailsConfig ?? new FeedbackFormEmails();

		if(!$formEmailsConfig->exists && $this->config['emails']){
			$formEmailsConfig->emails = $this->config['emails'];
			$formEmailsConfig->config = $this->config;
			$formEmailsConfig->code   = $this->config['code'];
			$formEmailsConfig->save();
		} else {
			$formEmailsConfig->config = $this->config;
		}

		if(\Auth::user() && \Auth::user()->hasAccessTo('cms')){
			$this->config['emails'] = $formEmailsConfig->emails;
		} else {
			unset($this->config['emails']);
		}
	}
}